version: '3.7'
services:

  php-fpm:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: boxes-php-fpm
    environment:
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      XDEBUG_CONFIG: "client_host=host.docker.internal"
    volumes:
      - ./:/var/www/html

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    container_name: boxes-nginx
    ports:
      - ${APP_WEB_PORT}:80
    environment:
      APP_WEB_PORT: ${APP_WEB_PORT}
      PHP_UPSTREAM_CONTAINER: php-fpm
      PHP_UPSTREAM_PORT: 9000
    depends_on:
      - php-fpm
    volumes:
      - ./web:/var/www/html/web